import Link from "next/link";
import { notFound } from "next/navigation";
import { obterContexto } from "@/server/auth/contexto";
import { buscarTarefaParaColaborador } from "@/lib/projetos-tarefas";
import { concluirTarefaFormAction } from "@/app/(painel)/projetos/actions";
import { Etiqueta } from "@/ui/campo";
const status: Record<string, string> = { A_INICIAR: "A iniciar", EM_ANDAMENTO: "Em andamento", AGUARDANDO_DOCUMENTO_CLIENTE: "Aguardando documento", VISITA_REUNIAO_AGENDADA: "Visita/reunião agendada", PROTOCOLADO: "Protocolado", SOB_ANALISE_ORGAO_AMBIENTAL: "Sob análise do órgão", COM_EXIGENCIA_A_CUMPRIR: "Com exigência", CONCLUIDO: "Concluída", CANCELADO: "Cancelada" };
const data = (v: Date | null) => v ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "UTC" }).format(v) : "—";
export default async function MinhaTarefaDetalhePage({ params }: { params: Promise<{ id: string }> }) { const ctx = await obterContexto(); const { id } = await params; const t = await buscarTarefaParaColaborador(ctx, id); if (!t) notFound(); return <div className="w-full max-w-[820px]"><Link href={ctx.perfil === "ADMIN_INTERNO" ? "/meus-projetos" : "/minhas-tarefas"} className="font-[family-name:var(--font-interface)] text-[14px] text-azul-esc">← Voltar</Link><div className="mt-5"><p className="text-[14px] text-cinza">{t.projeto.cliente.razaoSocial} · {t.projeto.nome}</p><div className="mt-1 flex flex-wrap items-center justify-between gap-3"><h1 className="text-[28px]">{t.nome}</h1><Etiqueta tom={t.status === "CONCLUIDO" ? "positivo" : undefined}>{status[t.status]}</Etiqueta></div><p className="mt-3 text-[15px] text-cinza">Prazo: <strong className="font-medium text-tinta">{data(t.prazo)}</strong></p></div>{t.descricao && <p className="mt-6 text-[15px] leading-7 text-cinza">{t.descricao}</p>}<section className="mt-8 border-t border-linha pt-6"><h2 className="text-[20px]">Checklist</h2><ul className="mt-4 overflow-hidden border border-linha bg-branco">{t.subtarefas.length === 0 ? <li className="px-5 py-6 text-[14px] text-cinza">Nenhum item de checklist.</li> : t.subtarefas.map(s => <li key={s.id} className="flex items-center gap-3 border-b border-linha px-5 py-3 last:border-b-0"><span className={`h-3 w-3 rounded-full ${s.concluida ? "bg-verde" : "border border-cinza"}`} /><span className={s.concluida ? "text-cinza line-through" : "text-tinta"}>{s.titulo}</span></li>)}</ul></section>{t.status !== "CONCLUIDO" && t.status !== "CANCELADO" && <form action={concluirTarefaFormAction.bind(null, t.id)} className="mt-8"><button className="min-h-11 rounded-[3px] bg-verde px-5 font-[family-name:var(--font-interface)] text-[14px] font-semibold text-tinta hover:bg-verde-esc hover:text-branco">Marcar como concluída</button><p className="mt-2 text-[13px] text-cinza">Essa é a única alteração disponível para a sua função.</p></form>}</div>; }
