import Link from "next/link";
import { exigirAcessoARota } from "@/server/auth/contexto";
import { listarClientesParaProjeto, listarItensAgenda, listarProjetos } from "@/lib/projetos-tarefas";
import { estaAtrasada } from "@/lib/regras-projetos-tarefas";
import { inputClass } from "@/ui/campo";

const nomesMeses = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
const semana = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];
const dataCurta = (v: Date) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", timeZone: "UTC" }).format(v);
const dataMes = (valor: string | undefined) => { const agora = new Date(); if (!valor || !/^\d{4}-\d{2}$/.test(valor)) return { ano: agora.getUTCFullYear(), mes: agora.getUTCMonth() }; const [ano, mes] = valor.split("-").map(Number); return { ano, mes: Math.min(11, Math.max(0, mes - 1)) }; };

export default async function AgendaPage({ searchParams }: { searchParams: Promise<{ mes?: string; projeto?: string; cliente?: string; visitas?: string }> }) {
  const ctx = await exigirAcessoARota("/agenda"); const filtros = await searchParams; const atual = dataMes(filtros.mes); const inicio = new Date(Date.UTC(atual.ano, atual.mes, 1)); const fim = new Date(Date.UTC(atual.ano, atual.mes + 1, 0, 23, 59, 59));
  const [itens, projetos, clientes] = await Promise.all([listarItensAgenda(ctx, inicio, fim, { projetoId: filtros.projeto, clienteId: filtros.cliente, visitas: filtros.visitas === "1" }), listarProjetos(ctx), listarClientesParaProjeto(ctx)]);
  const primeiroDia = inicio.getUTCDay(); const quantidadeDias = fim.getUTCDate(); const celulas = Array.from({ length: Math.ceil((primeiroDia + quantidadeDias) / 7) * 7 }, (_, i) => i - primeiroDia + 1); const porDia = new Map<number, typeof itens>(); for (const item of itens) { const dia = item.prazo.getUTCDate(); porDia.set(dia, [...(porDia.get(dia) ?? []), item]); }
  const anterior = new Date(Date.UTC(atual.ano, atual.mes - 1, 1)); const proximo = new Date(Date.UTC(atual.ano, atual.mes + 1, 1)); const hoje = new Date();
  const hrefMes = (d: Date) => `/agenda?mes=${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}${filtros.cliente ? `&cliente=${filtros.cliente}` : ""}${filtros.projeto ? `&projeto=${filtros.projeto}` : ""}${filtros.visitas ? "&visitas=1" : ""}`;
  return <div className="w-full max-w-[1240px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-[family-name:var(--font-interface)] text-[11px] font-semibold uppercase tracking-[0.12em] text-azul-esc">Calendário operacional</p><h1 className="mt-1 text-[28px]">Agenda</h1><p className="mt-1.5 text-[15px] text-cinza">Prazos materializados e próximas ocorrências da série.</p></div><div className="flex items-center gap-2 font-[family-name:var(--font-interface)]"><Link href={hrefMes(anterior)} aria-label="Mês anterior" className="flex h-10 w-10 items-center justify-center rounded-[3px] border border-linha text-[20px] hover:border-azul">‹</Link><span className="min-w-[150px] text-center text-[16px] font-semibold">{nomesMeses[atual.mes]} {atual.ano}</span><Link href={hrefMes(proximo)} aria-label="Próximo mês" className="flex h-10 w-10 items-center justify-center rounded-[3px] border border-linha text-[20px] hover:border-azul">›</Link><Link href="/agenda" className="ml-1 rounded-[3px] border border-linha px-3 py-2 text-[13px] hover:border-azul">Hoje</Link></div></div>
  <form className="mt-7 flex flex-wrap items-end gap-3"><label className="flex min-w-[220px] flex-col gap-1.5"><span className="font-[family-name:var(--font-interface)] text-[13px] font-medium">Cliente</span><select name="cliente" defaultValue={filtros.cliente ?? ""} className={inputClass}><option value="">Todos os clientes</option>{clientes.map(c => <option key={c.id} value={c.id}>{c.razaoSocial}</option>)}</select></label><label className="flex min-w-[220px] flex-col gap-1.5"><span className="font-[family-name:var(--font-interface)] text-[13px] font-medium">Projeto</span><select name="projeto" defaultValue={filtros.projeto ?? ""} className={inputClass}><option value="">Todos os projetos</option>{projetos.map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label className="flex min-h-11 items-center gap-2 pb-2 text-[14px]"><input type="checkbox" name="visitas" value="1" defaultChecked={filtros.visitas === "1"} className="h-4 w-4 accent-verde" />Só visitas/reuniões</label><button className="min-h-11 rounded-[3px] border border-linha px-4 font-[family-name:var(--font-interface)] text-[14px] hover:border-azul">Filtrar agenda</button></form>
  <div className="mt-7 overflow-hidden border border-linha bg-branco"><div className="grid grid-cols-7 border-b border-linha bg-tinta text-center font-[family-name:var(--font-interface)] text-[11px] font-semibold uppercase tracking-[0.06em] text-branco">{semana.map(d => <div key={d} className="px-1 py-3">{d}</div>)}</div><div className="grid grid-cols-7">{celulas.map((dia, i) => { if (dia < 1 || dia > quantidadeDias) return <div key={`vazio-${i}`} className="min-h-[135px] border-b border-r border-linha bg-papel/60" />; const data = new Date(Date.UTC(atual.ano, atual.mes, dia)); const doDia = porDia.get(dia) ?? []; const hojeCell = data.toISOString().slice(0, 10) === hoje.toISOString().slice(0, 10); return <div key={dia} className={`min-h-[135px] border-b border-r border-linha p-2 ${hojeCell ? "bg-verde-cl" : "bg-branco"}`}><span className={`font-[family-name:var(--font-interface)] text-[13px] ${hojeCell ? "rounded-full bg-verde px-2 py-1 font-semibold" : "text-cinza"}`}>{dia}</span><div className="mt-2 space-y-1">{doDia.slice(0, 3).map(item => { const atrasada = estaAtrasada(item.prazo, item.status === "CONCLUIDO", hoje); return item.projetada ? <div key={item.id} className="border-l-2 border-dashed border-azul bg-azul-cl px-2 py-1 text-[11px] text-tinta" title="Ocorrência projetada"><span className="block truncate font-medium">{item.nome}</span><span className="text-azul-esc">Próxima ocorrência</span></div> : <Link key={item.id} href={`/tarefas/${item.id}`} className={`block border-l-2 px-2 py-1 text-[11px] hover:underline ${atrasada ? "border-l-vermelho bg-vermelho-cl" : item.status === "VISITA_REUNIAO_AGENDADA" ? "border-l-ambar bg-ambar/8" : "border-l-verde bg-verde-cl"}`}><span className="block truncate font-medium">{item.nome}</span><span className="block truncate text-cinza">{item.projeto.cliente.razaoSocial}</span></Link>; })}{doDia.length > 3 && <details className="text-[11px] text-azul-esc"><summary className="cursor-pointer">+{doDia.length - 3} mais</summary><div className="mt-1 space-y-1">{doDia.slice(3).map(item => <p key={item.id} className="truncate">{item.nome} · {dataCurta(item.prazo)}</p>)}</div></details>}</div></div>; })}</div></div>
  {itens.length === 0 && <p className="mt-5 text-center text-[14px] text-cinza">Nenhum prazo neste mês.</p>}<div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 font-[family-name:var(--font-interface)] text-[12px] text-cinza"><span><i className="mr-1 inline-block h-2.5 w-2.5 border-l-2 border-l-verde bg-verde-cl" />Prazo normal</span><span><i className="mr-1 inline-block h-2.5 w-2.5 border-l-2 border-l-vermelho bg-vermelho-cl" />Atrasado</span><span><i className="mr-1 inline-block h-2.5 w-2.5 border-l-2 border-l-ambar bg-ambar/8" />Visita/reunião</span><span><i className="mr-1 inline-block h-2.5 w-2.5 border-l-2 border-dashed border-l-azul bg-azul-cl" />Ocorrência projetada</span></div></div>;
}
