import Link from "next/link";
import { exigirAcessoARota } from "@/server/auth/contexto";
import { indicadorDePrazos, listarClientesParaProjeto, listarPrazos, listarProjetos } from "@/lib/projetos-tarefas";
import { estaAtrasada } from "@/lib/regras-projetos-tarefas";
import { Etiqueta, inputClass } from "@/ui/campo";

const data = (v: Date | null) => v ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "UTC" }).format(v) : "Sem prazo";
const hoje = new Date();
const status: Record<string, string> = { A_INICIAR: "A iniciar", EM_ANDAMENTO: "Em andamento", AGUARDANDO_DOCUMENTO_CLIENTE: "Aguardando documento", VISITA_REUNIAO_AGENDADA: "Visita/reunião agendada", PROTOCOLADO: "Protocolado", SOB_ANALISE_ORGAO_AMBIENTAL: "Sob análise do órgão", COM_EXIGENCIA_A_CUMPRIR: "Com exigência", CONCLUIDO: "Concluída", CANCELADO: "Cancelada" };

export default async function PrazosPage({ searchParams }: { searchParams: Promise<{ projeto?: string; cliente?: string; todos?: string }> }) {
  const ctx = await exigirAcessoARota("/prazos");
  const filtros = await searchParams;
  const pendentes = filtros.todos !== "1";
  const [tarefas, projetos, clientes] = await Promise.all([
    listarPrazos(ctx, { projetoId: filtros.projeto, clienteId: filtros.cliente, pendentes }),
    listarProjetos(ctx),
    listarClientesParaProjeto(ctx),
  ]);
  const indicador = indicadorDePrazos(tarefas);
  return <div className="w-full max-w-[1120px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-[family-name:var(--font-interface)] text-[11px] font-semibold uppercase tracking-[0.12em] text-azul-esc">Visão gerencial</p><h1 className="mt-1 text-[28px]">Painel de Prazos</h1><p className="mt-1.5 text-[15px] text-cinza">A fila de entregas que precisa ser acompanhada hoje.</p></div><div className="border-l-[3px] border-ambar bg-branco px-5 py-3"><p className="text-[11px] uppercase tracking-[0.08em] text-cinza">Em dia</p><p className="font-[family-name:var(--font-interface)] text-[25px] font-semibold text-tinta">{indicador.percentual === null ? "—" : `${indicador.percentual}%`} <span className="text-[13px] font-normal text-cinza">({indicador.emDia}/{indicador.total})</span></p></div></div>
    <form className="mt-7 flex flex-wrap items-end gap-3"><label className="flex min-w-[230px] flex-col gap-1.5"><span className="font-[family-name:var(--font-interface)] text-[13px] font-medium">Cliente</span><select name="cliente" defaultValue={filtros.cliente ?? ""} className={inputClass}><option value="">Todos os clientes</option>{clientes.map(c => <option key={c.id} value={c.id}>{c.razaoSocial}</option>)}</select></label><label className="flex min-w-[230px] flex-col gap-1.5"><span className="font-[family-name:var(--font-interface)] text-[13px] font-medium">Projeto</span><select name="projeto" defaultValue={filtros.projeto ?? ""} className={inputClass}><option value="">Todos os projetos</option>{projetos.map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label className="flex min-h-11 items-center gap-2 pb-2 text-[14px]"><input type="checkbox" name="todos" value="1" defaultChecked={!pendentes} className="h-4 w-4 accent-verde" />Mostrar concluídas</label><button className="min-h-11 rounded-[3px] border border-linha px-4 font-[family-name:var(--font-interface)] text-[14px] hover:border-azul">Filtrar prazos</button></form>
    {tarefas.length === 0 ? <div className="mt-8 border border-dashed border-linha bg-branco px-8 py-14 text-center"><p className="text-[17px] text-tinta">Nenhum prazo nesta seleção.</p><p className="mt-2 text-[14px] text-cinza">A fila está limpa ou os filtros não encontraram tarefas.</p></div> : <><div className="mt-7 hidden overflow-hidden border border-linha bg-branco md:block"><table className="w-full border-collapse font-[family-name:var(--font-interface)] text-[14px]"><thead><tr className="bg-tinta text-left text-branco"><th className="rounded-l-[3px] px-5 py-3 text-[11px] uppercase tracking-[0.06em]">Tarefa</th><th className="px-5 py-3 text-[11px] uppercase tracking-[0.06em]">Projeto / cliente</th><th className="px-5 py-3 text-[11px] uppercase tracking-[0.06em]">Prazo</th><th className="px-5 py-3 text-[11px] uppercase tracking-[0.06em]">Status</th><th className="rounded-r-[3px] px-5 py-3" /></tr></thead><tbody>{tarefas.map(t => { const atrasada = estaAtrasada(t.prazo, t.status === "CONCLUIDO", hoje); return <tr key={t.id} className={`border-t border-linha ${atrasada ? "border-l-[3px] border-l-vermelho bg-vermelho-cl" : "hover:bg-verde-cl"}`}><td className="px-5 py-4 font-medium"><Link href={`/tarefas/${t.id}`} className="hover:text-azul-esc">{t.nome}</Link>{t.responsavel && <span className="ml-2 text-[12px] font-normal text-cinza">· {t.responsavel.nome}</span>}</td><td className="px-5 py-4 text-cinza">{t.projeto.nome}<span className="block text-[12px]">{t.projeto.cliente.razaoSocial}</span></td><td className={`px-5 py-4 tabular-nums ${atrasada ? "font-semibold text-vermelho" : "text-tinta"}`}>{data(t.prazo)}{atrasada && <span className="ml-2 text-[11px] uppercase">atrasada</span>}</td><td className="px-5 py-4"><Etiqueta tom={atrasada ? "atencao" : t.status === "CONCLUIDO" ? "positivo" : undefined}>{status[t.status]}</Etiqueta></td><td className="px-5 py-4 text-right"><Link href={`/tarefas/${t.id}`} className="text-azul-esc hover:underline">Detalhe</Link></td></tr>; })}</tbody></table></div><ul className="mt-7 space-y-2 md:hidden">{tarefas.map(t => { const atrasada = estaAtrasada(t.prazo, t.status === "CONCLUIDO", hoje); return <li key={t.id} className={`border-l-[3px] bg-branco px-4 py-4 ${atrasada ? "border-l-vermelho" : "border border-linha border-l-azul"}`}><Link href={`/tarefas/${t.id}`} className="block"><div className="flex justify-between gap-3"><p className="font-[family-name:var(--font-interface)] font-medium">{t.nome}</p><Etiqueta tom={atrasada ? "atencao" : undefined}>{atrasada ? "Atrasada" : data(t.prazo)}</Etiqueta></div><p className="mt-1 text-[13px] text-cinza">{t.projeto.nome} · {t.projeto.cliente.razaoSocial}</p></Link></li>; })}</ul></>}</div>;
}
