import Link from "next/link";
import { exigirAcessoARota } from "@/server/auth/contexto";
import { listarTarefasAtribuidas } from "@/lib/projetos-tarefas";
import { Etiqueta } from "@/ui/campo";
import { buscarLimitesSemaforo } from "@/lib/semaforo";
import { IndicadorSemaforoProjeto } from "@/ui/indicador-dias-restantes";
import { calcularPercentualConclusao } from "@/lib/regras-projetos-tarefas";
import { IndicadorConclusao } from "@/ui/indicador-conclusao";
const status: Record<string, string> = { A_INICIAR: "A iniciar", EM_ANDAMENTO: "Em andamento", AGUARDANDO_DOCUMENTO_CLIENTE: "Aguardando documento", VISITA_REUNIAO_AGENDADA: "Visita/reunião agendada", PROTOCOLADO: "Protocolado", SOB_ANALISE_ORGAO_AMBIENTAL: "Sob análise do órgão", COM_EXIGENCIA_A_CUMPRIR: "Com exigência", CONCLUIDO: "Concluída", CANCELADO: "Cancelada" };
export default async function MinhasTarefasPage() { const ctx = await exigirAcessoARota("/minhas-tarefas"); const [tarefas, limites] = await Promise.all([listarTarefasAtribuidas(ctx), buscarLimitesSemaforo(ctx)]); return <div className="w-full max-w-[1000px]"><h1 className="text-[28px]">Minhas tarefas</h1><p className="mt-1.5 text-[15px] text-cinza">O que precisa da sua atenção, em ordem de prazo.</p>{tarefas.length === 0 ? <div className="mt-8 border border-dashed border-linha bg-branco px-8 py-14 text-center text-[15px] text-cinza">Nenhuma tarefa atribuída a você ainda.</div> : <div className="mt-7 overflow-hidden border border-linha bg-branco">{tarefas.map(t => { const progresso = t.subtarefas.length ? calcularPercentualConclusao(t.subtarefas) : calcularPercentualConclusao([{ ativo: true, status: t.status }]); return <Link href={`/minhas-tarefas/${t.id}`} key={t.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-linha px-5 py-4 hover:bg-verde-cl last:border-b-0"><div className="min-w-0"><p className="font-[family-name:var(--font-interface)] text-[15px] font-semibold text-tinta">{t.nome}</p><p className="mt-1 text-[14px] text-cinza">{t.projeto.cliente.razaoSocial} · {t.projeto.nome}</p><p className="mt-2 text-[13px] text-cinza">Progresso: <IndicadorConclusao indicador={progresso} detalhado />{t.subtarefas.length ? " subtarefas" : ""}</p>{t._count.subtarefas > 0 && <p className="mt-1 text-[12px] font-medium text-ambar">{t._count.subtarefas} {t._count.subtarefas === 1 ? "subtarefa aguarda" : "subtarefas aguardam"} atribuição</p>}</div><div className="flex shrink-0 items-center gap-4"><span className="text-right font-[family-name:var(--font-interface)] text-[13px] text-cinza"><span className="block text-[11px] uppercase tracking-[0.06em]">Prazo</span><IndicadorSemaforoProjeto prazo={t.prazo} status={t.status} limites={limites} /></span><Etiqueta tom={t.status === "CONCLUIDO" ? "positivo" : undefined}>{status[t.status]}</Etiqueta></div></Link>; })}</div>}</div>; }
