import { listarComentarios, type AlvoComentario } from "@/lib/comentarios";
import { criarComentarioAction } from "./actions";
import { inputClass } from "@/ui/campo";
import { obterContexto } from "@/server/auth/contexto";

export async function Comentarios({ alvo, nivel, entidadeId, tarefaId }: { alvo: AlvoComentario; nivel: "projeto" | "tarefa" | "subtarefa"; entidadeId: string; tarefaId?: string }) {
  const comentarios = await listarComentarios(await obterContexto(), alvo);
  return <section className="mt-9 max-w-[760px] border-t border-linha pt-6"><h2 className="text-[21px]">Comentários <span className="font-[family-name:var(--font-interface)] text-[14px] text-cinza">({comentarios.length})</span></h2>{comentarios.length > 0 && <ol className="mt-4 space-y-3">{comentarios.map(c => <li key={c.id} className="border-l-[3px] border-l-azul bg-branco px-5 py-4"><div className="flex flex-wrap justify-between gap-2 font-[family-name:var(--font-interface)] text-[12px] text-cinza"><strong className="font-semibold text-tinta">{c.autor.nome}</strong><time>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(c.criadoEm)}</time></div><p className="mt-2 whitespace-pre-wrap text-[14px] leading-6 text-tinta">{c.texto}</p>{c.link && <a href={c.link} target="_blank" rel="noreferrer" className="mt-2 inline-block font-[family-name:var(--font-interface)] text-[13px] text-azul-esc hover:underline">Abrir link ↗</a>}</li>)}</ol>}<form action={criarComentarioAction} className="mt-4 rounded-[3px] border border-linha bg-branco p-4"><input type="hidden" name="nivel" value={nivel} /><input type="hidden" name="entidadeId" value={entidadeId} />{tarefaId && <input type="hidden" name="tarefaId" value={tarefaId} />}<textarea name="texto" required rows={3} placeholder="Escreva uma atualização para este item" className={inputClass} /><input name="link" type="url" placeholder="Link opcional" className={`${inputClass} mt-2`} /><button className="mt-3 min-h-10 rounded-[3px] bg-tinta px-4 font-[family-name:var(--font-interface)] text-[13px] font-semibold text-branco">Publicar comentário</button></form></section>;
}
