import Link from "next/link";
import { notFound } from "next/navigation";
import { exigirAcessoARota } from "@/server/auth/contexto";
import { buscarTarefa } from "@/lib/projetos-tarefas";
import { concluirSubtarefaAction, concluirTarefaAction, criarSubtarefaAction } from "@/app/(painel)/projetos/actions";
import { Etiqueta, inputClass } from "@/ui/campo";
const statuses: Record<string, string> = { A_INICIAR: "A iniciar", EM_ANDAMENTO: "Em andamento", AGUARDANDO_DOCUMENTO_CLIENTE: "Aguardando documento", VISITA_REUNIAO_AGENDADA: "Visita/reunião agendada", PROTOCOLADO: "Protocolado", SOB_ANALISE_ORGAO_AMBIENTAL: "Sob análise do órgão", COM_EXIGENCIA_A_CUMPRIR: "Com exigência", CONCLUIDO: "Concluído", CANCELADO: "Cancelado" };
const data = (v: Date | null) => v ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "UTC" }).format(v) : "—";
export default async function TarefaDetalhePage({ params }: { params: Promise<{ id: string }> }) {
  const ctx = await exigirAcessoARota("/tarefas"); const { id } = await params; const t = await buscarTarefa(ctx, id, true); if (!t) notFound();
  return <div className="w-full max-w-[980px]"><Link href={`/projetos/${t.projetoId}`} className="font-[family-name:var(--font-interface)] text-[14px] text-azul-esc hover:underline">← {t.projeto.nome}</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-[14px] text-cinza">{t.projeto.cliente.razaoSocial}</p><h1 className="mt-1 text-[28px]">{t.nome}</h1><p className="mt-2 text-[15px] text-cinza">Prazo: <strong className="font-medium text-tinta">{data(t.prazo)}</strong>{t.responsavel ? ` · Responsável: ${t.responsavel.nome}` : ""}</p></div><div className="flex flex-wrap gap-2"><Etiqueta tom={t.ativo ? undefined : "apagado"}>{t.ativo ? statuses[t.status] : "Desativada"}</Etiqueta><Link href={`/tarefas/${id}/editar`} className="rounded-[3px] border border-linha px-3 py-2 font-[family-name:var(--font-interface)] text-[13px] hover:border-azul">Editar</Link>{t.status !== "CONCLUIDO" && <form action={concluirTarefaAction.bind(null, id)}><button className="rounded-[3px] bg-verde px-3 py-2 font-[family-name:var(--font-interface)] text-[13px] font-semibold text-tinta">Marcar como concluída</button></form>}</div></div>{t.descricao && <p className="mt-6 max-w-[70ch] text-[15px] text-cinza">{t.descricao}</p>}
  <section className="mt-9 max-w-[760px]"><div className="flex items-center justify-between gap-3"><h2 className="text-[21px]">Checklist <span className="font-[family-name:var(--font-interface)] text-[14px] text-cinza">({t.subtarefas.filter(s => s.concluida).length}/{t.subtarefas.length})</span></h2></div><div className="mt-4 overflow-hidden rounded-[3px] border border-linha bg-branco">{t.subtarefas.length === 0 ? <p className="px-5 py-8 text-[14px] text-cinza">Nenhum item ainda. Adicione os passos necessários para concluir a tarefa.</p> : t.subtarefas.map(s => <div key={s.id} className="flex items-center justify-between gap-4 border-b border-linha px-5 py-3 last:border-b-0"><div className="flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${s.concluida ? "bg-verde" : "border border-cinza"}`} /><div><p className={s.concluida ? "text-cinza line-through" : "text-tinta"}>{s.titulo}</p>{s.etiquetas.length > 0 && <p className="mt-1 font-[family-name:var(--font-interface)] text-[12px] text-cinza">{s.etiquetas.join(" · ")}</p>}</div></div>{!s.concluida && <form action={concluirSubtarefaAction.bind(null, s.id)}><button className="font-[family-name:var(--font-interface)] text-[13px] text-azul-esc hover:underline">Concluir</button></form>}</div>)}</div><form action={criarSubtarefaAction} className="mt-4 grid gap-2 rounded-[3px] border border-linha bg-branco p-4 sm:grid-cols-[1fr_220px_auto]"><input type="hidden" name="tarefaId" value={t.id} /><input name="titulo" required placeholder="Novo item do checklist" className={inputClass} /><input name="etiquetas" placeholder="Etiquetas, separadas por vírgula" className={inputClass} /><button className="min-h-11 rounded-[3px] bg-tinta px-4 font-[family-name:var(--font-interface)] text-[13px] font-semibold text-branco">Adicionar</button></form></section></div>;
}
