import { notFound } from "next/navigation";
import { exigirAcessoARota } from "@/server/auth/contexto";
import { buscarProjeto, listarPessoasParaProjeto } from "@/lib/projetos-tarefas";
import { criarTarefaERedirecionarAction } from "../../../actions";
import { Campo, SecaoNumerada, inputClass } from "@/ui/campo";
export default async function NovaTarefaPage({ params }: { params: Promise<{ id: string }> }) {
  const ctx = await exigirAcessoARota("/projetos"); const { id } = await params; const projeto = await buscarProjeto(ctx, id); if (!projeto) notFound(); const pessoas = await listarPessoasParaProjeto(ctx, projeto.clienteId);
  return <div className="w-full max-w-[820px]"><a href={`/projetos/${id}`} className="font-[family-name:var(--font-interface)] text-[14px] text-azul-esc">← {projeto.nome}</a><h1 className="mt-4 text-[28px]">Nova tarefa</h1><form action={criarTarefaERedirecionarAction} className="mt-8 space-y-8"><input type="hidden" name="projetoId" value={id} /><SecaoNumerada numero="01" titulo="Tarefa"><Campo label="Nome da tarefa" obrigatorio><input name="nome" required className={inputClass} placeholder="Ex.: Protocolar renovação" /></Campo><Campo label="Descrição"><textarea name="descricao" rows={4} className={inputClass} /></Campo><div className="grid gap-4 sm:grid-cols-2"><Campo label="Responsável"><select name="responsavelId" className={inputClass}><option value="">Sem responsável</option>{pessoas.map(p => <option key={p.id} value={p.id}>{p.nome}{p.temAcesso ? " · acesso ativo" : ""}</option>)}</select></Campo><Campo label="Prazo" obrigatorio><input type="date" name="prazo" required className={inputClass} /></Campo></div></SecaoNumerada><SecaoNumerada numero="02" titulo="Acompanhamento"><div className="grid gap-4 sm:grid-cols-3"><Campo label="Status"><select name="status" defaultValue="A_INICIAR" className={inputClass}><option value="A_INICIAR">A iniciar</option><option value="EM_ANDAMENTO">Em andamento</option><option value="AGUARDANDO_DOCUMENTO_CLIENTE">Aguardando documento do cliente</option><option value="VISITA_REUNIAO_AGENDADA">Visita/reunião agendada</option><option value="PROTOCOLADO">Protocolado</option><option value="SOB_ANALISE_ORGAO_AMBIENTAL">Sob análise do órgão ambiental</option><option value="COM_EXIGENCIA_A_CUMPRIR">Com exigência a cumprir</option><option value="CONCLUIDO">Concluído</option><option value="CANCELADO">Cancelado</option></select></Campo><Campo label="Periodicidade"><select name="periodicidade" defaultValue="" className={inputClass}><option value="">Sem recorrência</option><option value="SEMANAL">Semanal</option><option value="MENSAL">Mensal</option><option value="TRIMESTRAL">Trimestral</option><option value="SEMESTRAL">Semestral</option><option value="ANUAL">Anual</option></select></Campo><Campo label="Antecedência (dias)"><input type="number" min="1" name="diasAntecedencia" className={inputClass} placeholder="Padrão: 7" /></Campo></div></SecaoNumerada><div className="flex gap-3"><button className="min-h-11 rounded-[3px] bg-verde px-5 text-[14px] font-semibold text-tinta">Criar tarefa</button><a href={`/projetos/${id}`} className="flex min-h-11 items-center rounded-[3px] border border-linha px-5 text-[14px]">Cancelar</a></div></form></div>;
}
